### ISSUE TITLE
Patch server started with file not issues error on M1 Mac

### ISSUE THREAD

**Issue by tomkxy** [afs/rdf-delta#131]
Although, this is not a serious issue for me, I just realized that the Patchlog server would not work using a file on M1 Mac.
```
./dcmd server --store PatchStore
[2022-01-03 15:14:07] Delta      INFO  Provider: Local
[2022-01-03 15:14:07] Config     INFO  Delta Server port=1066
[2022-01-03 15:14:07] Delta      INFO  RDF Delta 1.1.0 2021-12-19T17:55:49+0000
[2022-01-03 15:14:07] Delta      INFO    No data sources
[2022-01-03 15:14:34] Delta      ERROR /private/var/folders/30/xrq32v4j71lg9g74s44bv8n00000gq/T/librocksdbjni8940527698892575582.jnilib: dlopen(/private/var/folders/30/xrq32v4j71lg9g74s44bv8n00000gq/T/librocksdbjni8940527698892575582.jnilib, 0x0001): tried: '/private/var/folders/30/xrq32v4j71lg9g74s44bv8n00000gq/T/librocksdbjni8940527698892575582.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni8940527698892575582.jnilib' (no such file)
java.lang.UnsatisfiedLinkError: /private/var/folders/30/xrq32v4j71lg9g74s44bv8n00000gq/T/librocksdbjni8940527698892575582.jnilib: dlopen(/private/var/folders/30/xrq32v4j71lg9g74s44bv8n00000gq/T/librocksdbjni8940527698892575582.jnilib, 0x0001): tried: '/private/var/folders/30/xrq32v4j71lg9g74s44bv8n00000gq/T/librocksdbjni8940527698892575582.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni8940527698892575582.jnilib' (no such file)
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:746) ~[?:?]
	at java.lang.System.load(System.java:1857) ~[?:?]
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79) ~[delta-server.jar:?]
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57) ~[delta-server.jar:?]
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:69) ~[delta-server.jar:?]
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.patchstores.rdb.RocksDatabase.<clinit>(RocksDatabase.java:29) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.patchstores.rdb.PatchStoreRocks.lambda$newPatchLog$1(PatchStoreRocks.java:90) ~[delta-server.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at org.seaborne.delta.server.local.patchstores.rdb.PatchStoreRocks.newPatchLog(PatchStoreRocks.java:85) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.PatchStore.createPatchLog(PatchStore.java:310) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.PatchStore.createLog(PatchStore.java:239) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.patchstores.any.PatchStoreAnyLocal.newPatchLog(PatchStoreAnyLocal.java:91) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.PatchStore.createPatchLog(PatchStore.java:310) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.PatchStore.createLog(PatchStore.java:239) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.LocalServer.createDataSource$(LocalServer.java:353) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.LocalServer.createDataSource(LocalServer.java:335) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.LocalServer.createDataSource(LocalServer.java:315) ~[delta-server.jar:?]
	at org.seaborne.delta.server.local.DeltaLinkLocal.newDataSource(DeltaLinkLocal.java:99) ~[delta-server.jar:?]
	at org.seaborne.delta.server.http.S_DRPC.createDataSource(S_DRPC.java:354) ~[delta-server.jar:?]
	at org.seaborne.delta.server.http.S_DRPC.executeAction(S_DRPC.java:175) ~[delta-server.jar:?]
	at org.seaborne.delta.server.http.DeltaServlet.doCommon(DeltaServlet.java:147) ~[delta-server.jar:?]
	at org.seaborne.delta.server.http.S_DRPC.doPost(S_DRPC.java:60) ~[delta-server.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:523) ~[delta-server.jar:?]
	at org.seaborne.delta.server.http.DeltaServlet.service(DeltaServlet.java:87) ~[delta-server.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[delta-server.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[delta-server.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1624) ~[delta-server.jar:?]
	at org.seaborne.delta.server.http.F_PatchFilter.doFilter(F_PatchFilter.java:77) ~[delta-server.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[delta-server.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594) ~[delta-server.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[delta-server.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:418) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:675) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:410) ~[delta-server.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[delta-server.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[delta-server.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[delta-server.jar:?]
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101) ~[delta-server.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[delta-server.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[delta-server.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[delta-server.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[delta-server.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407) [delta-server.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [delta-server.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [delta-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
Exception is thrown when trying to start a Fuseki instance:
```
./dcmd fuseki --port 3031 --conf fuseki-config1.ttl               
[2022-01-03 15:14:34] Delta      INFO  Delta Patch Log Servers: [http://localhost:1066/]
[2022-01-03 15:14:34] Zone       INFO  Connection : /Users/A71396588/Documents/projects/rdf-delta-1.1.0/Zone1/ABC
[2022-01-03 15:14:34] HTTP       WARN  Failed : create_datasource {  "name" : "ABC" , "uri" : "delta:ABC" }
500 - Server Error
```

**Comment by afs** [comment]
RocksDB Java is not yet available for M1 Mac. Close, but not there yet (as of 2021-01-03).

https://github.com/facebook/rocksdb/issues/7720
